[tool.poetry]
name = "manage-joboffers"
version = "0.1.0"
description = ""
authors = ["andrzej <andrzej.b.czajka@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
